add installation from source
gwastro/gwin pull request #53
Opened 2018-07-18 21:23 UTC by Cyberface

addressing issue https://github.com/gwastro/gwin/issues/31

2018-07-18 22:20 UTC, cdcapano requested changes
Thanks for tackling this. I think we want to provide instructions both for installing a release and installing from source. So, please keep the current instructions as-is, but add another section about how to install from source into a virtualenv. Also, I would not include anything about cloning, since that is in the `contributing.md`. Just start with assuming someone has cloned, and instruct them to go into their cloned source code directory.

2018-07-18 22:20 UTC, cdcapano commented on README.rst
> +   ccd gwin
This should be `cd`.

2018-07-19 08:29 UTC, duncanmmacleod submitted a review, later dismissed
LGTM

2018-07-19 18:04 UTC, cdcapano approved these changes
Happy

2018-07-19 18:53 UTC, merged