Standardize the stats returned by the models
gwastro/gwin pull request #62
Opened 2018-07-20 03:04 UTC by cdcapano

This ensures that all models return at least `logjacobian`, `logprior`, and `loglikelihood` in their default statistics. Models that inherit from `BaseModel` may add additional statistics using the `_extra_stats` property. This is used by `BaseDataModel`, `GaussianNoise`, and `MarginalizedPhaseGaussianNoise`.

For the `GaussianNoise` model, the loglikelihood is saved to the current stats when `loglr` is called, to ensure that the current stats are appropriately populated, even if `loglikelihood` is not called.

2018-07-27 09:43 UTC, cdcapano commented
@vivienr poke

2018-07-27 14:38 UTC, vivienr requested changes

2018-07-27 14:38 UTC, vivienr commented on gwin/models/gaussian_noise.py
> +        detctor."""
detctor -> detector

2018-07-27 14:39 UTC, vivienr commented on gwin/models/gaussian_noise.py
> +        detctor."""
other that this tiny typo, looks good to me !

2018-08-03 09:16 UTC, cdcapano commented
@vivienr I fixed the typo. I also rebased to master to include Charlie's changes to the marginalized gaussian noise model.

2018-08-03 11:26 UTC, vivienr approved these changes

2018-08-03 11:49 UTC, merged